using BepInEx;using BepInEx.Configuration;using HarmonyLib;using System;using System.Collections.Generic;using System.Diagnostics;using System.Reflection;using System.Reflection.Emit;
namespace ElonaLuckForElinV3{
[BepInPlugin(G,N,V)]public sealed class Plugin:BaseUnityPlugin{
public const string G="sivwen.elin.elonaluck",N="Elona Luck for Elin v3.3.1 Safe",V="3.3.1";
internal static Plugin I=null!;Harmony? h;
internal static ConfigEntry<bool> Witness=null!,Lock=null!,Fish=null!,Activity=null!,Mine=null!,Dig=null!,Harvest=null!,FishBonus=null!,Craft=null!,Casino=null!,StealWeight=null!,SeedLuck=null!,TreasureLuck=null!,ScratchLuck=null!,FertEggLuck=null!;
internal static ConfigEntry<int> WitnessDiv=null!,WitnessCap=null!,LockDiv=null!,LockCap=null!,FishDiv=null!,FishCap=null!,SkillW=null!,LuckW=null!,CasinoDiv=null!,CasinoCap=null!,StealWeightDiv=null!,StealWeightCap=null!,SeedDiv=null!,SeedCap=null!,TreasureDiv=null!,TreasureCap=null!,ScratchDiv=null!,ScratchCap=null!,EggDiv=null!,EggCap=null!;
void Awake(){I=this;
Witness=Config.Bind("범죄/발각 운","범죄 목격 회피 운",true,"범죄 목격 판정에만 운을 적용합니다.");WitnessDiv=Config.Bind("범죄/발각 운","목격 회피 운 분모",25,"기본 회피 확률은 운/이 값(%)입니다.");WitnessCap=Config.Bind("범죄/발각 운","목격 회피 확률 상한",60,"목격 회피 확률 상한입니다.");
Lock=Config.Bind("자물쇠 운","자물쇠 따기 운",true,"자물쇠 따기 시 유효 자물쇠 레벨만 일시적으로 낮춥니다.");LockDiv=Config.Bind("자물쇠 운","자물쇠 운 분모",20,"감소량은 운/이 값입니다.");LockCap=Config.Bind("자물쇠 운","자물쇠 레벨 감소 상한",100,"감소량 상한입니다.");
Fish=Config.Bind("낚시 운","낚시 품질 운",true,"잡힌 물고기의 tier를 운에 따라 1단계 올립니다.");FishDiv=Config.Bind("낚시 운","낚시 품질 운 분모",25,"등급 상승 확률은 운/이 값(%)입니다.");FishCap=Config.Bind("낚시 운","낚시 품질 확률 상한",50,"등급 상승 확률 상한입니다.");
Activity=Config.Bind("SkillAndLuckMatter 대체","활동 보너스 사용",true,"스킬+운 활동 보너스를 사용합니다.");Mine=Config.Bind("SkillAndLuckMatter 대체","채광 보너스",true,"채광 보너스입니다.");Dig=Config.Bind("SkillAndLuckMatter 대체","땅파기 보너스",true,"땅파기 보너스입니다.");Harvest=Config.Bind("SkillAndLuckMatter 대체","수확/채집/벌목 보너스",true,"수확·채집·벌목 보너스입니다.");FishBonus=Config.Bind("SkillAndLuckMatter 대체","낚시 보너스",true,"낚시 수량 보너스입니다.");Craft=Config.Bind("SkillAndLuckMatter 대체","제작/가공 재료 환급",true,"제작/가공 재료 환급입니다.");SkillW=Config.Bind("SkillAndLuckMatter 대체","스킬 가중치",3,"스킬 가중치입니다.");LuckW=Config.Bind("SkillAndLuckMatter 대체","운 가중치",2,"운 가중치입니다.");
Casino=Config.Bind("카지노 운","카지노 배당 운",true,"순이익에 운 보너스를 적용합니다.");CasinoDiv=Config.Bind("카지노 운","카지노 보너스 운 분모",25,"추가 배당 확률은 운/이 값(%)입니다.");CasinoCap=Config.Bind("카지노 운","카지노 보너스 확률 상한",50,"추가 배당 확률 상한입니다.");
StealWeight=Config.Bind("훔치기 운","중량 제한 운 우회",true,"AI_Steal 내부 tooHeavy 판정만 확률적으로 우회합니다.");StealWeightDiv=Config.Bind("훔치기 운","중량 우회 운 분모",20,"기본 우회 확률은 운/이 값(%)입니다.");StealWeightCap=Config.Bind("훔치기 운","중량 우회 확률 상한",75,"기본 우회 확률 상한입니다.");
SeedLuck=Config.Bind("채집/농사 운","씨앗 회수 운",true,"TryPopSeed의 첫 RNG만 보정합니다.");SeedDiv=Config.Bind("채집/농사 운","씨앗 운 분모",25,"운 보정 분모입니다.");SeedCap=Config.Bind("채집/농사 운","씨앗 보너스 상한",60,"상대 보너스 상한입니다.");
TreasureLuck=Config.Bind("보물상자 운","보물 장비 희귀도 운",true,"CreateTreasureContent의 SetRarity 로컬 RNG만 보정합니다.");TreasureDiv=Config.Bind("보물상자 운","보물 희귀도 운 분모",25,"운 보정 분모입니다.");TreasureCap=Config.Bind("보물상자 운","보물 희귀도 보너스 상한",75,"상대 보너스 상한입니다.");
ScratchLuck=Config.Bind("스크래치 운","스크래치 당첨 운",true,"TraitCrafter의 Prize 로컬 RNG만 보정합니다.");ScratchDiv=Config.Bind("스크래치 운","스크래치 운 분모",25,"운 보정 분모입니다.");ScratchCap=Config.Bind("스크래치 운","스크래치 보너스 상한",75,"상대 보너스 상한입니다.");
FertEggLuck=Config.Bind("생산 운","수정란 운",true,"플레이어 진영 MakeEgg의 fertChance만 보정합니다.");EggDiv=Config.Bind("생산 운","수정란 운 분모",25,"운 보정 분모입니다.");EggCap=Config.Bind("생산 운","수정란 보너스 상한",75,"상대 보너스 상한입니다.");
h=new Harmony(G);
Patch("범죄 목격",typeof(WitnessPatch));Patch("자물쇠",typeof(LockPatch));Patch("낚시 품질",typeof(FishPatch));Patch("활동 보너스",typeof(ActivityPatch));Patch("낚시 수량",typeof(FishBonusPatch));Patch("제작 환급",typeof(RecipePatch));Patch("제작 환급 카드",typeof(RecipeCardPatch));Patch("카지노",typeof(CasinoPatch));Patch("훔치기 시도 난수",typeof(StealAttemptRollPatch));Patch("훔치기 중량",typeof(StealWeightNarrowPatch));Patch("씨앗",typeof(SeedLuckNarrowPatch));Patch("수정란",typeof(FertEggLuckNarrowPatch));Patch("스크래치",typeof(ScratchPrizeNarrowPatch));Patch("보물상자",typeof(TreasureRarityNarrowPatch));
Logger.LogInfo(N+" "+V+" loaded. SpawnLoot/Card.Die 패치 없음.");}
void Patch(string name,Type t){try{h!.CreateClassProcessor(t).Patch();Logger.LogInfo("[Luck] "+name+": 적용");}catch(Exception e){Logger.LogWarning("[Luck] "+name+": 비활성 ("+e.GetType().Name+") "+e.Message);}}
void OnDestroy(){h?.UnpatchSelf();}
internal static int Luck(){int l=EClass.pc==null?1:EClass.pc.Evalue(78);return Math.Max(1,Math.Min(9999,l));}
internal static int Rel(ConfigEntry<int>d,ConfigEntry<int>c)=>Math.Min(Math.Max(0,c.Value),Math.Max(0,Luck()/Math.Max(1,d.Value)));
internal static int Reduce(int d,int b){if(d<=1||b<=0)return d;return Math.Max(1,(int)(((long)d*100L+99+b)/(100+b)));}
internal static double Score(int s){int sw=Math.Max(0,SkillW.Value),lw=Math.Max(0,LuckW.Value),den=sw+lw;if(den<=0)return 0;return (Math.Max(0,s)*sw+Luck()*lw)/(double)den;}
internal static double Curve(double x){if(x<=0)return 0;if(x<10)return x/10*.15;if(x<40)return .15+(x-10)/30*.35;if(x<100)return .5+(x-40)/60*.25;if(x<200)return .75+(x-100)/100*.25;return 1+(x-200)/100;}
internal static int Rolls(int s,bool craft=false){double p=Curve(Score(s));if(craft)p/=10;int n=(int)Math.Floor(p);double f=p-n;if(f>0&&EClass.rnd(100000)<(int)(f*100000))n++;return n;}
}
[HarmonyPatch(typeof(Point),nameof(Point.TryWitnessCrime),new Type[]{typeof(Chara),typeof(Chara),typeof(int),typeof(Func<Chara,bool>)})]static class WitnessPatch{static void Prefix(Chara criminal,ref Func<Chara,bool> funcWitness){if(!Plugin.Witness.Value||criminal==null||EClass.pc==null||criminal!=EClass.pc)return;int a=Math.Min(Plugin.WitnessCap.Value,Plugin.Luck()/Math.Max(1,Plugin.WitnessDiv.Value));if(a<=0)return;var old=funcWitness;if(old==null)funcWitness=c=>EClass.rnd(10)==0&&EClass.rnd(100)>=a;else funcWitness=c=>old(c)&&EClass.rnd(100)>=a;}}
[HarmonyPatch(typeof(Trait),nameof(Trait.TryOpenLock),new Type[]{typeof(Chara),typeof(bool)})]static class LockPatch{public sealed class S{public int lv;public bool changed;}static void Prefix(Trait __instance,Chara cc,out S __state){__state=new S();if(!Plugin.Lock.Value||cc==null||!cc.IsPC||__instance.owner==null)return;int cut=Math.Min(Plugin.LockCap.Value,Plugin.Luck()/Math.Max(1,Plugin.LockDiv.Value));__state.lv=__instance.owner.c_lockLv;int n=Math.Max(0,__state.lv-cut);if(n<__state.lv){__instance.owner.c_lockLv=n;__state.changed=true;}}static Exception? Finalizer(Trait __instance,S __state,Exception? e){if(__state!=null&&__state.changed&&__instance.owner.c_lockLv>0)__instance.owner.c_lockLv=__state.lv;return e;}}
[HarmonyPatch(typeof(AI_Fish),nameof(AI_Fish.Makefish),new Type[]{typeof(Chara)})]static class FishPatch{static void Postfix(Chara c,ref Thing __result){if(!Plugin.Fish.Value||c==null||!c.IsPC||__result==null||__result.category==null||!__result.category.IsChildOf("fish"))return;int a=Math.Min(Plugin.FishCap.Value,Plugin.Luck()/Math.Max(1,Plugin.FishDiv.Value));if(__result.tier<3&&EClass.rnd(100)<a)__result.SetTier(Math.Min(3,__result.tier+1));}}
[HarmonyPatch(typeof(Map),nameof(Map.TrySmoothPick),new Type[]{typeof(Point),typeof(Thing),typeof(Chara)})]static class ActivityPatch{static void Prefix(Thing t,Chara c){if(!Plugin.Activity.Value||t==null||c==null||!c.IsPC)return;var fs=new StackTrace(1,false).GetFrames();if(fs==null)return;int skill=-1;bool on=false;for(int i=0;i<fs.Length&&i<12;i++){string n=fs[i].GetMethod()?.DeclaringType?.FullName??"";if(n.Contains("TaskMine")){skill=c.Evalue(220);on=Plugin.Mine.Value;break;}if(n.Contains("TaskDig")){skill=c.Evalue(230);on=Plugin.Dig.Value;break;}if(n.Contains("TaskChopWood")){skill=c.Evalue(225);on=Plugin.Harvest.Value;break;}if(n.Contains("TaskHarvest")||n.Contains("GrowSystem")){skill=Math.Max(c.Evalue(250),c.Evalue(286));on=Plugin.Harvest.Value;break;}}if(!on||skill<0)return;int r=Plugin.Rolls(skill);if(r>0){int b=Math.Max(1,t.Num);t.ModNum(b*r);}}}
[HarmonyPatch(typeof(AI_Fish),nameof(AI_Fish.Makefish),new Type[]{typeof(Chara)})]static class FishBonusPatch{static void Postfix(Chara c,ref Thing __result){if(!Plugin.Activity.Value||!Plugin.FishBonus.Value||c==null||!c.IsPC||__result==null)return;int r=Plugin.Rolls(c.Evalue(245));if(r>0){int b=Math.Max(1,__result.Num);__result.ModNum(b*r);}}}
static class CraftCore{internal static List<Thing>? Prep(Recipe r,List<Thing> ings,bool model){if(!Plugin.Activity.Value||!Plugin.Craft.Value||model||r==null||ings==null||EClass.pc==null)return null;Element e=r.source?.GetReqSkill();int rr=Plugin.Rolls(e==null?0:EClass.pc.Evalue(e.id),true);if(rr<=0)return null;var z=new List<Thing>();foreach(var x in ings)if(x!=null)z.Add(x.Duplicate(Math.Max(1,x.Num)*rr));return z;}internal static void Give(List<Thing>?xs){if(xs==null)return;foreach(var x in xs)EClass.pc.AddCard(x);}}
[HarmonyPatch(typeof(Recipe),nameof(Recipe.Craft),new Type[]{typeof(BlessedState),typeof(bool),typeof(List<Thing>),typeof(TraitCrafter),typeof(bool)})]static class RecipePatch{static void Prefix(Recipe __instance,List<Thing> ings,bool model,out List<Thing>? __state){__state=CraftCore.Prep(__instance,ings,model);}static void Postfix(List<Thing>? __state,Thing __result){if(__result!=null)CraftCore.Give(__state);}}
[HarmonyPatch(typeof(RecipeCard),nameof(RecipeCard.Craft),new Type[]{typeof(BlessedState),typeof(bool),typeof(List<Thing>),typeof(TraitCrafter),typeof(bool)})]static class RecipeCardPatch{static void Prefix(RecipeCard __instance,List<Thing> ings,bool model,out List<Thing>? __state){__state=CraftCore.Prep(__instance,ings,model);}static void Postfix(List<Thing>? __state,Thing __result){if(__result!=null)CraftCore.Give(__state);}}
[HarmonyPatch(typeof(MiniGame),nameof(MiniGame.Deactivate),new Type[]{})]static class CasinoPatch{static void Prefix(MiniGame __instance){if(!Plugin.Casino.Value||__instance?.balance==null||__instance.balance.changeCoin<=0)return;int a=Math.Min(Plugin.CasinoCap.Value,Plugin.Luck()/Math.Max(1,Plugin.CasinoDiv.Value));if(EClass.rnd(100)<a)__instance.balance.changeCoin+=Math.Max(1,__instance.balance.changeCoin/2);}}
static class StealAttemptContext{[ThreadStatic]internal static int roll;[ThreadStatic]internal static bool has;}
[HarmonyPatch(typeof(AI_Steal),nameof(AI_Steal.Perform),new Type[]{})]static class StealAttemptRollPatch{static void Prefix(){StealAttemptContext.roll=EClass.rnd(10000);StealAttemptContext.has=true;}}
[HarmonyPatch]static class StealWeightNarrowPatch{static readonly MethodInfo Getter=typeof(Card).GetProperty("ChildrenAndSelfWeight",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)?.GetGetMethod(true)!;static readonly MethodInfo Helper=typeof(StealWeightNarrowPatch).GetMethod(nameof(EffectiveWeight),BindingFlags.Static|BindingFlags.NonPublic)!;static IEnumerable<MethodBase> TargetMethods(){foreach(var t in Nested(typeof(AI_Steal)))foreach(var m in t.GetMethods(BindingFlags.Instance|BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic))if(!m.IsAbstract&&!m.ContainsGenericParameters&&Calls(m))yield return m;}static IEnumerable<Type> Nested(Type r){foreach(var t in r.GetNestedTypes(BindingFlags.Public|BindingFlags.NonPublic)){yield return t;foreach(var c in Nested(t))yield return c;}}static bool Calls(MethodBase m){if(Getter==null)return false;try{var il=m.GetMethodBody()?.GetILAsByteArray();if(il==null)return false;int tok=Getter.MetadataToken;for(int i=0;i+4<il.Length;i++){byte op=il[i];if((op==0x28||op==0x6f)&&BitConverter.ToInt32(il,i+1)==tok)return true;}}catch{}return false;}static long EffectiveWeight(Card target){long w=target==null?0:target.ChildrenAndSelfWeight;if(!Plugin.StealWeight.Value||target==null||EClass.pc==null)return w;long limit=(long)EClass.pc.Evalue(281)*200L+(long)EClass.pc.STR*100L+1000L;if(w<=limit||limit<=0)return w;int b=Math.Min(Plugin.StealWeightCap.Value,Plugin.Luck()/Math.Max(1,Plugin.StealWeightDiv.Value));int chance=(int)Math.Max(1L,Math.Min(b,(long)b*limit/Math.Max(1L,w)));if(!StealAttemptContext.has){StealAttemptContext.roll=EClass.rnd(10000);StealAttemptContext.has=true;}return StealAttemptContext.roll<chance*100?limit:w;}static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> ins){foreach(var ci in ins){if(Getter!=null&&ci.operand is MethodInfo m&&m==Getter&&(ci.opcode==OpCodes.Call||ci.opcode==OpCodes.Callvirt))yield return new CodeInstruction(OpCodes.Call,Helper);else yield return ci;}}}
[HarmonyPatch(typeof(GrowSystem),nameof(GrowSystem.TryPopSeed),new Type[]{typeof(Chara)})]static class SeedLuckNarrowPatch{static readonly MethodInfo Rnd=typeof(EClass).GetMethod(nameof(EClass.rnd),new Type[]{typeof(int)})!;static readonly MethodInfo Helper=typeof(SeedLuckNarrowPatch).GetMethod(nameof(SeedRnd),BindingFlags.Static|BindingFlags.NonPublic)!;static int SeedRnd(int max,Chara c){if(!Plugin.SeedLuck.Value||c==null||!c.IsPC)return EClass.rnd(max);return EClass.rnd(Plugin.Reduce(max,Plugin.Rel(Plugin.SeedDiv,Plugin.SeedCap)));}static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> ins){int n=0;foreach(var ci in ins){if(ci.operand is MethodInfo m&&m==Rnd&&(ci.opcode==OpCodes.Call||ci.opcode==OpCodes.Callvirt)&&n++==0){yield return new CodeInstruction(OpCodes.Ldarg_1);yield return new CodeInstruction(OpCodes.Call,Helper);}else yield return ci;}}}
[HarmonyPatch(typeof(Card),nameof(Card.MakeEgg),new Type[]{typeof(bool),typeof(int),typeof(bool),typeof(int),typeof(BlessedState?)})]static class FertEggLuckNarrowPatch{static void Prefix(Card __instance,ref int fertChance){if(!Plugin.FertEggLuck.Value||__instance==null||!__instance.IsPCFaction||fertChance<=1)return;fertChance=Plugin.Reduce(fertChance,Plugin.Rel(Plugin.EggDiv,Plugin.EggCap));}}
[HarmonyPatch]static class ScratchPrizeNarrowPatch{static readonly MethodInfo Rnd=typeof(EClass).GetMethod(nameof(EClass.rnd),new Type[]{typeof(int)})!;static readonly MethodInfo Helper=typeof(ScratchPrizeNarrowPatch).GetMethod(nameof(R),BindingFlags.Static|BindingFlags.NonPublic)!;static IEnumerable<MethodBase> TargetMethods(){foreach(var m in Methods(typeof(TraitCrafter)))if(m.Name.Contains("g__Prize"))yield return m;}static IEnumerable<MethodBase> Methods(Type r){foreach(var m in r.GetMethods(BindingFlags.Static|BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic))yield return m;foreach(var t in r.GetNestedTypes(BindingFlags.Public|BindingFlags.NonPublic))foreach(var m in Methods(t))yield return m;}static int R(int max){return !Plugin.ScratchLuck.Value||max<=1?EClass.rnd(max):EClass.rnd(Plugin.Reduce(max,Plugin.Rel(Plugin.ScratchDiv,Plugin.ScratchCap)));}static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> ins){foreach(var ci in ins){if(ci.operand is MethodInfo m&&m==Rnd&&(ci.opcode==OpCodes.Call||ci.opcode==OpCodes.Callvirt))yield return new CodeInstruction(OpCodes.Call,Helper);else yield return ci;}}}
[HarmonyPatch]static class TreasureRarityNarrowPatch{static readonly MethodInfo Rnd=typeof(EClass).GetMethod(nameof(EClass.rnd),new Type[]{typeof(int)})!;static readonly MethodInfo Helper=typeof(TreasureRarityNarrowPatch).GetMethod(nameof(R),BindingFlags.Static|BindingFlags.NonPublic)!;static IEnumerable<MethodBase> TargetMethods(){foreach(var m in Methods(typeof(ThingGen)))if(m.Name.Contains("g__SetRarity"))yield return m;}static IEnumerable<MethodBase> Methods(Type r){foreach(var m in r.GetMethods(BindingFlags.Static|BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic))yield return m;foreach(var t in r.GetNestedTypes(BindingFlags.Public|BindingFlags.NonPublic))foreach(var m in Methods(t))yield return m;}static int R(int max){return !Plugin.TreasureLuck.Value||(max!=100&&max!=20)?EClass.rnd(max):EClass.rnd(Plugin.Reduce(max,Plugin.Rel(Plugin.TreasureDiv,Plugin.TreasureCap)));}static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> ins){foreach(var ci in ins){if(ci.operand is MethodInfo m&&m==Rnd&&(ci.opcode==OpCodes.Call||ci.opcode==OpCodes.Callvirt))yield return new CodeInstruction(OpCodes.Call,Helper);else yield return ci;}}}
}
